name: Probe and Deploy
on:
  # Setting this enables manually triggering workflow in the GitHub UI
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: {}

permissions: read-all

jobs:
  run_prober:
    runs-on: ubuntu-latest
    steps:
      - name: check out pr branch
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build browser testing container
        env:
          DOCKER_BUILDKIT: 1
        run: bin/build-browser-tests
      - name: Run prober test
        run: bin/run-prober
        env:
          TEST_USER_LOGIN: ${{ secrets.TEST_USER_LOGIN }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      - name: Promote to prod.
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: cloud/deploys/seattle/bin/deploy-prod
